services:
  - type: web
    name: waqf-scraper-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    disk:
      name: pdf-storage
      mountPath: /opt/render/project/src/backend/pdf_output
      sizeGB: 5

  - type: web
    name: waqf-scraper-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://waqf-scraper-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
